name: czinkos
description: Blogging about stuffs
meta_description: "czinkos"

pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog url'
author:         'czinkos'
